USE hotel_management;

SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM payment;
DELETE FROM invoice_detail;
DELETE FROM invoice;
DELETE FROM service_usage;
DELETE FROM booking;
DELETE FROM room;
DELETE FROM room_type;
DELETE FROM service;
DELETE FROM customer;
DELETE FROM employee;

ALTER TABLE payment AUTO_INCREMENT = 1;
ALTER TABLE invoice_detail AUTO_INCREMENT = 1;
ALTER TABLE invoice AUTO_INCREMENT = 1;
ALTER TABLE service_usage AUTO_INCREMENT = 1;
ALTER TABLE booking AUTO_INCREMENT = 1;
ALTER TABLE room AUTO_INCREMENT = 1;
ALTER TABLE room_type AUTO_INCREMENT = 1;
ALTER TABLE service AUTO_INCREMENT = 1;
ALTER TABLE customer AUTO_INCREMENT = 1;
ALTER TABLE employee AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
SET SQL_SAFE_UPDATES = 1;
